# Generated by Django 6.1.1 on 2026-09-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('colour', models.CharField(choices=[('#FFF4A3', 'Yellow'), ('#FFC6C6', 'Pink'), ('#C9F2C9', 'Green'), ('#C6E2FF', 'Blue'), ('#E5D4FF', 'Purple')], default='#FFF4A3', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
